# BUCKET - User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-user-bucket
spec:
  title: User
  description: User of the forum
  icon: assignment
  primary: username
  readOnly: false
  history: false
  properties:
    username:
      type: string
      title: username
      description: Description of the username input
      options:
        position: bottom
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    surname:
      type: string
      title: surname
      description: Description of the surname input
      options:
        position: bottom
    email:
      type: string
      title: email
      description: Description of the email input
      options:
        position: bottom
      pattern: .+@.+\..+
    birthday:
      type: date
      title: birthday
      description: Description of the birthday input
      options:
        position: bottom
    gender:
      type: string
      title: gender
      description: Description of the gender input
      options:
        position: bottom
      enum:
        - Male
        - Female
        - Other
    level:
      type: string
      title: level
      description: Description of the level input
      options:
        position: bottom
      enum:
        - rookie
        - experienced
        - master
    followings:
      type: relation
      title: followings
      description: Description of the followings input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    followers:
      type: relation
      title: followers
      description: Description of the followers input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    profile_picture:
      type: storage
      title: profile_picture
      description: Description of the profile_picture input
      options:
        position: bottom
    bio:
      type: textarea
      title: bio
      description: Description of the bio input
      options:
        position: bottom
    identity_id:
      type: string
      title: identity_id
      description: Description of the identity_id input
      options:
        position: bottom
  acl:
    write: true == true
    read: true == true
  order: 5
---
# BUCKET - Category
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-category-bucket
spec:
  title: Category
  description: Category of the Forum
  icon: assignment
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    titles:
      type: relation
      title: titles
      description: Description of the titles input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-title-bucket
    surveys:
      type: relation
      title: surveys
      description: Description of the surveys input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-survey-bucket
    popularity:
      type: number
      title: popularity
      description: Description of the popularity input
      options:
        position: bottom
      minimum: 0
      maximum: 100
  acl:
    write: true==true
    read: true==true
  order: 6
---
# BUCKET - Title
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-title-bucket
spec:
  title: Title
  description: Title of the forum
  icon: assignment
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    content:
      type: string
      title: content
      description: Description of the content
      options:
        position: bottom
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    comments:
      type: relation
      title: comments
      description: Description of the comments input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-comment-bucket
    created_at:
      type: date
      title: date
      description: Description of the date input
      options:
        position: bottom
      default: created_at
  acl:
    write: true == true
    read: true==true
  order: 7
---
# BUCKET - Comment
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-comment-bucket
spec:
  title: Comment
  description: Comment of the Forum
  icon: assignment
  primary: content
  readOnly: false
  history: false
  properties:
    content:
      type: string
      title: content
      description: Description of the content input
      options:
        position: bottom
    date:
      type: date
      title: date
      description: Description of the date input
      options:
        position: bottom
      default: :created_at
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    likes:
      type: relation
      title: likes
      description: Description of the likes input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    dislikes:
      type: relation
      title: dislikes
      description: Description of the dislikes input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    images:
      type: array
      title: images
      description: Description of the images input
      options:
        position: bottom
      items:
        title: Title of the items
        type: storage
    is_post:
      type: boolean
      title: is_post
      description: Description of the is_post input
      options:
        position: bottom
    comments:
      type: relation
      title: comments
      description: Description of the comments input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-comment-bucket
    category:
      type: relation
      title: category
      description: Description of the category input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-category-bucket
  acl:
    write: true == true
    read: true==true
  order: 8
---
# BUCKET - Survey
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-survey-bucket
spec:
  title: Survey
  description: Survey of the forum
  icon: assignment
  primary: title
  readOnly: false
  history: false
  properties:
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    title:
      type: string
      title: title
      description: Description of the title input
      options:
        position: bottom
    selections:
      type: array
      title: options
      items:
        type: object
        properties:
          option:
            type: string
            title: Name
          voter:
            type: relation
            title: voter
            description: Description of the voter input
            options:
              position: bottom
            relationType: onetomany
            dependent: false
            bucket:
              resourceFieldRef:
                schemaName: spica-forum-asset-user-bucket
        title: selections
      options:
        position: bottom
  acl:
    write: true == true
    read: true==true
  order: 9
---
# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: forum-asset-apikey
spec:
  name: Secret Api Key For Forum
  policies:
    - BucketFullAccess
    - FunctionFullAccess
    - IdentityFullAccess
---
# FUNCTION - Forum Authorization
apiVersion: function/v1
kind: Function
metadata:
  name: spica-forum-asset-authorization-function
spec:
  language: javascript
  timeout: 25
  description: Authorization process
  environment:
    - name: USER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    - name: SECRET_API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: forum-asset-apikey
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "@spica-devkit/identity"
      version: latest
  title: Forum Authorization
  code: ./function/spica-forum-asset-authorization-function.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - register
apiVersion: function/v1
kind: Trigger
metadata:
  name: register
spec:
  type: http
  active: true
  name: register
  func: spica-forum-asset-authorization-function
  httpOptions:
    method: Post
    path: /register